### ISSUE TITLE
CentOS Scripted Install - Incorrect Directory

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#1011]
You need to replace the parts of this template where you see {{some text}}.

**Version**
2.0.5

**Steps to reproduce the bug**
1. Install LL via script (on CentOS)
2. Create org, email, pw via prompts
3. Error displays

**Expected behaviour**
Should complete installation

**Actual behaviour**
The following error is displayed:
[LL] Attempt to manually start the Mongo service and then run this command:
[LL] cd /usr/local/learninglocker/releases/ll-20171024-5040772f24d33ccc3f0e9a8b142f9f0c3a25f3a3; node cli/dist/server createSiteAdmin YOUR.EMAIL@ADDRESS.COM ORGANISATION_NAME YOUR_PASSWORD
module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/learninglocker/releases/ll-20171024-5040772f24d33ccc3f0e9a8b142f9f0c3a25f3a3/webapp/cli/dist/server'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Additional information**
OS: CentOS 7.4

It looks like the correct directory to execute the command is: webapp/cli/src/commands

**Comment by davidpesce** [comment]
Trying to launch pm2 manually and the following directories appear to be wrong as well:
[PM2][ERROR] script not found : /usr/local/learninglocker/releases/ll-20171024-5040772f24d33ccc3f0e9a8b142f9f0c3a25f3a3/webapp/api/dist/server
[PM2][ERROR] script not found : /usr/local/learninglocker/releases/ll-20171024-5040772f24d33ccc3f0e9a8b142f9f0c3a25f3a3/webapp/ui/dist/server
[PM2][ERROR] script not found : /usr/local/learninglocker/releases/ll-20171024-5040772f24d33ccc3f0e9a8b142f9f0c3a25f3a3/webapp/worker/dist/server

"dist" should be replaced with "src"

**Comment by ht2** [comment]
Thanks for this David. Just FYI - the `dist/` is there as this is where the built output is for each of these commands. Calling on the files in the `src/` would not work as everything has to be compiled through Webpack first.

However something is clearly going wrong. What would be very helpful to myself and @gardron is if you could locate the `/var/log/learninglocker/install.log` and upload a copy to here (or pastebin etc) so we could establish exactly what has happened.

**Comment by fishfree** [comment]
In Ubuntu 16.04, the same problem.

**Comment by gardron** [comment]
Ok, this isn't something we've seen before - if you can upload your install.log then we can take a look through and identify and fix the problem. It sounds like something specific to your setup but again, it's not something we've run into before. Don't mind if it's the log from centos or ubuntu, either will do if it's failing on both platforms.
Thanks.

**Comment by davidpesce** [comment]
I'm looking in the logs folder and don't see an install log. Is there somewhere else I should be looking?

**Comment by davidpesce** [comment]
Nvm, I'm a dolt. RTFM. I didn't scan the whole thing, but is there any data I wouldn't want to share publicly?

**Comment by davidpesce** [comment]
Following up here rather than gitter.

NGINX
I just did a fresh install of centos on digitalocean and attempted to install nginx via yum. The package doesn’t exist. Installing epel-release and then attempting again, finds nginx and allows it be installed. Success!

It looks like line 879 (llv2_build.sh) needs to have “redhat_epel” added to it to invoke the install of epel-release.

MONGODB
Digging a bit deeper, the version of mongodb-server included with epel-release does not meet the requirements of LLv2. It only contains mongoldb-server 2.6.12: http://mirror.math.princeton.edu/pub/epel/7/x86_64/Packages/m/mongodb-server-2.6.12-4.el7.x86_64.rpm

When I create a separate yum repo for mongodb-org, the rest of the automated script works. Here's the instructions: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/#configure-the-package-management-system-yum

**Comment by davidpesce** [comment]
For anyone stumbling on this in the meantime, here's what is somewhat working for me:

1. yum update
2. yum install epel-release
3. yum install nginx
4. Follow instructions here: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/#configure-the-package-management-system-yum
5. yum install redis
6. Execute LLv2 install script via curl

It fails to launch at the end, but I think that's due to the directory being incorrect...

**Comment by davidpesce** [comment]
Here's the output from the final part of the launch script:

[PM2] Spawning PM2 daemon with pm2_home=/usr/local/learninglocker/releases/.pm2
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications API, UIServer, Worker not running, starting...
[PM2][ERROR] script not found : /usr/local/learninglocker/current/webapp/api/dist/server
[PM2][ERROR] script not found : /usr/local/learninglocker/current/webapp/ui/dist/server
[PM2][ERROR] script not found : /usr/local/learninglocker/current/webapp/worker/dist/server
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
done[LL] starting xapi process....[PM2][WARN] Applications xAPI not running, starting...
[PM2][ERROR] script not found : /usr/local/learninglocker/current/xapi/dist/server.js
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
done[PM2] Saving current process list...
[PM2] Successfully saved in /usr/local/learninglocker/releases/.pm2/dump.pm2
[LL] setting up PM2 startup
Created symlink from /etc/systemd/system/multi-user.target.wants/pm2-learninglocker.service to /etc/systemd/system/pm2-learninglocker.service.
Redirecting to /bin/systemctl start pm2-learninglocker.service
[LL] do you want to set up the organisation now to complete the installation? [y|n] (press enter for the default of 'y')
[LL] please enter the organisation name
Exputo
[LL] please enter the email address for the administrator account
david.pesce@exputo.com
[LL] please enter the password for the administrator account
[LL] please confirm the password for the administrator account

[LL] Is the following information correct?
[LL] Organisation : Exputo
[LL] Email address : david.pesce@exputo.com
[LL] [y|n]
[LL] Attempting to create your site admin. If this step fails, then it is possible Mongo has not started.
[LL] Attempt to manually start the Mongo service and then run this command:
[LL] cd /usr/local/learninglocker/releases/ll-20171101-b69600374d54c0354ba79ca259f9e55e3d6fab54; node cli/dist/server createSiteAdmin YOUR.EMAIL@ADDRESS.COM ORGANISATION_NAME YOUR_PASSWORD
module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/learninglocker/releases/ll-20171101-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/cli/dist/server'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

Thanks for installing Learning Locker v2

If you need to add a new superuser (other than one created by the install process) then you can run this command:
    cd ${LOCAL_PATH}; node cli/dist/server createSiteAdmin "EMAIL" "ORG-NAME" "PASSWD"
 with replacing the values in capitals with ones you want

If you need to restart the services this script has installed then you can run this command:
    service pm2-learninglocker restart

[LL] cleaning up temp directories

**Comment by ht2** [comment]
Closing due to inactivity, think this may be resolved in later version of the deploy script
