### ISSUE TITLE
createSiteAdmin fails with "No matching document found" error

### ISSUE THREAD

**Issue by kaaloo** [LearningLocker/learninglocker#1014]
**Version**
develop at 5530c1f1ed2e305db64f33d211bb7115c2acfab8 on 2.0.5 

**Steps to reproduce the bug**
1. Run the `createSiteAdmin` cli command on a brand new mongo db

**Expected behaviour**
`createSiteAdmin` should successfully create the user and organisation.

**Actual behaviour**
`createSiteAdmin` fails with the following stack trace:

```
2017-10-25 19:53:42:098 - info: Looking for "luis@testing.local"
2017-10-25 19:53:42:239 - info: User not found, creating...
(node:7) DeprecationWarning: Implicit async custom validators (custom validators that take 2 arguments) are deprecated in mongoose >= 4.9.0. See http://mongoosejs.com/docs/validation.html#async-custom-validators for more info.
2017-10-25 19:53:43:103 - info: Organisation not found, creating...
2017-10-25 19:53:43:313 - error: No matching document found for id "59f0ebc6de78f00007dcfd15"
2017-10-25 19:53:43:313 - error:  Error
    at model.wrappedPointCut [as save] (/app/node_modules/mongoose/lib/services/model/applyHooks.js:123:29)
    at _callee4$ (/app/cli/dist/server/webpack:/commands/createSiteAdmin.js:50:14)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise (<anonymous>)
    at F (/app/node_modules/core-js/library/modules/_export.js:35:28)
    at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at ensureUserHasOrg (/app/cli/dist/server/index.js:5119:18)
    at _callee6$ (/app/cli/dist/server/webpack:/commands/createSiteAdmin.js:95:9)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

**Additional information**
OS: Alpine Linux 3.6 (using node:alpine docker image)

**Comment by ht2** [comment]
Hi Kaloo, we're aware of the Error message, but I don't believe this action has failed. Both the organisation and user have been created and you should be able to access Learning Locker using the credentials you entered. We'll look further into the error message but I do not believe it is critical, as it relates giving an organisation admin role to your new user, which is set to be a Site Admin anyway (and therefore has the privileges already)

**Comment by kaaloo** [comment]
Thank you so much for your quick update.  I'm sorry my report was incomplete in the sense that I neglected to mention that I am not able to actually log in.  I get the error "Incorrect login credentials" as below.

![selection_001](https://user-images.githubusercontent.com/67010/32050234-5b3a09f4-ba50-11e7-8b8d-62e849f10dfb.png)

Do you have any suggestions to debug this ?

**Comment by ht2** [comment]
If you look in the Mongo database I'm pretty sure you will see that the user exists, more likely you missed typed the password, or entered it in an unexpected format when prompted by the script.

Out of interest, did you manually run the CLI command, or was this part of the install script?

**Comment by kaaloo** [comment]
Indeed I just checked the db and I see both my user and organisation.  Yay!  Unfortunately I'm still locked out.

In the nginx logs I see the login POST request returning a 401

`172.17.0.8 - luis@mookyskills.com [26/Oct/2017:12:17:06 +0000] "POST /api/auth/jwt/password HTTP/1.1" 401 53 "http://locker/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"`

I did run the CLI command manually as follows:

`node cli/dist/server createSiteAdmin "${ADMIN_EMAIL}" "${ADMIN_ORGANISATION}" "${ADMIN_PASSWORD}"`

**Comment by ht2** [comment]
Silly question, did you remove the `$`, and `{}` when you ran the command? 
http://docs.learninglocker.net/guides-cli/#createsiteadmin

**Comment by kaaloo** [comment]
Oh no worries, the following env vars are defined when the `createSideAdmin` command runs:

- `ADMIN_EMAIL`
- `ADMIN_ORGANISATION`
- `ADMIN_PASSWORD`

And furthermore I did find the correct entries in the db.  I'm working on setting up a dev environment so I can debug.  Learning a lot in the process ! :)

**Comment by kaaloo** [comment]
Thanks for your help!  It turns out this was a silly error setting the above mentioned env vars.
