### ISSUE TITLE
AMI LearningLocker issue

### ISSUE THREAD

**Issue by caperneoignis** [LearningLocker/learninglocker#1104]
**Version**
2.1.2

**Steps to reproduce the bug**
1.  node cli/dist/server createSiteAdmin "lee.a.kirkland@gmail.com" "NewOrg" "Som3Pa55Word"

**Expected behaviour**
Creates new admin and org with no issues. 

**Actual behaviour**
```` bash
2018-02-05 16:14:04:765 - info: Looking for lee.a.kirkland@gmail.com
2018-02-05 16:14:04:816 - info: User not found, creating...
(node:8811) DeprecationWarning: Implicit async custom validators (custom validators that take 2 arguments) are deprecated in mongoose >= 4.9.0. See http://mongoosejs.com/docs/validation.html#async-custom-validators for more info.
2018-02-05 16:14:04:953 - info: Organisation not found, creating...
2018-02-05 16:14:05:064 - error: No matching document found for id "5a7882cc90513d226bc9ca9e"
2018-02-05 16:14:05:065 - error:  Error
    at model.wrappedPointCut [as save] (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/mongoose/lib/services/model/applyHooks.js:123:29)
    at _callee4$ (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/cli/dist/server/webpack:/commands/createSiteAdmin.js:50:14)
    at tryCatch (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/core-js/library/modules/_export.js:35:28)
    at /usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at ensureUserHasOrg (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/cli/dist/server/index.js:5186:18)
    at _callee6$ (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/cli/dist/server/webpack:/commands/createSiteAdmin.js:95:9)
    at tryCatch (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13

````

**Additional information**
OS: AMI Image with MongDB and Redis setup as separate instances. 
Browser: N/A

I have also been having issue with XAPI service worker getting statements from Mongo. Not sure if they are related. 

```` bash
3|xAPI     | 2018-02-05 16:07:59:207 - error: fbaed968-af41-4037-9640-8bbd3abdca11: jscommons handled - Unauthorised
3|xAPI     | 2018-02-05 16:08:29:207 - error: 970bc5a4-e961-4e06-a5f4-6c5d7d79982f: jscommons handled - Unauthorised
3|xAPI     | 2018-02-05 16:08:59:171 - error: d756ca87-0daa-4f0e-af26-b328d328116c: jscommons handled - Unauthorised
`````

However, After running the above command again, I can log in using the email and creds supplied. Not sure why workers are throwing connection errors even though I can still log in. But this is effecting tincan statements being pulled from the system by the workers, but not the creation of the statements.

So, not sure if they are linked or not. But the Mongo is the same version that would be installed by the deploy script, since I just used the command in the deploy script to install mongo for Ubuntu and updated the .env files from both Xapi and Webapp to use the remote Mongo. 

I also setup Mongo to listen to 0.0.0.0 on the default port. 

I also received the same errors when running the AMI with default settings so it was using the Mongo and redis server locally on the server.

**Comment by caperneoignis** [comment]
Never mind on the Unauthorized piece. It ended up being a setting in the module I was using to work with Moodle and Learninglocker. I turned that setting off and the Unauthorized went away.

**Comment by ht2** [comment]
To confirm - the error in the create admin via CLI is a known "side effect" and not actually an error. Glad you sorted your issue.

**Comment by DiazHub** [comment]
> Never mind on the Unauthorized piece. It ended up being a setting in the module I was using to work with Moodle and Learninglocker. I turned that setting off and the Unauthorized went away.

@caperneoignis Would you please elaborate on the setting you're talking about? I am experiencing identical statements from the xapi_1 worker and it is preventing our  learning activities from performing GET & PUT to our LL instance.

**Comment by caperneoignis** [comment]
@DiazHub I believe the way I fixed it was to first update it after starting up the AMI. Because the AMI was super old, unless they have updated it since the last time I started one of these bad boys from scratch. Updating it using the update script works as expected.

**Comment by caperneoignis** [comment]
The setting I was speaking of, was the tincan setting in xapi_tincanlaunch link module, or the xapi logstore one of the two had a setting for learninglocker.
