### ISSUE TITLE
Exception 'Locker\Helpers\Exceptions\Conflict' with message 'Conflicts ... - Seems to cause courses to freeze when it happens

### ISSUE THREAD

**Issue by mparnelldmp** [LearningLocker/learninglocker#1115]
**Version**
1.17.0

**Information**
Courses are built in Articulate Storyline - we've tried both versions 2 and 3 and this still seems to crop up. I suspect the courses have an issue somewhere and are trying to perform an operation that conflicts with an index somewhere.

I suspect this issue is causing a "freezing" issue within the courses themselves.

**Steps to reproduce the bug**
1. Take course, await errors in the log. This happens inconsistently.

```
[2018-02-28 18:07:55] local.ERROR: exception 'Locker\Helpers\Exceptions\Conflict' with message 'Conflicts
`{"version":"1.0.0","object":{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id\/5oX4dpMcZUI","definition":{"description":{"und":"great picking"},"name":{"und":"great picking"},"type":"http:\/\/adlnet.gov\/expapi\/activities\/module"}},"actor":{"objectType":"Agent","mbox":"mailto:REMOVED","name":"REMOVED"},"context":{"contextActivities":{"parent":[{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id"}],"grouping":[{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id"}]}},"verb":{"id":"http:\/\/adlnet.gov\/expapi\/verbs\/experienced"},"id":"ed9a911e-6111-4ea6-9d9b-57b881458d8f","authority":{"objectType":"Agent","name":"New Client","mbox":"mailto:hello@learninglocker.net"},"stored":"2018-02-28T18:07:55.632200+00:00","timestamp":"2018-02-28T18:07:55.632200+00:00"}`
`{"version":"1.0.0","actor":{"objectType":"Agent","mbox":"REMOVED","name":"REMOVED"},"context":{"contextActivities":{"parent":[{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id"}],"grouping":[{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id"}]}},"result":{"completion":false},"object":{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id","definition":{"description":{"und":""},"name":{"und":"DMP Responsiveness Part 2 Value Video"},"type":"http:\/\/adlnet.gov\/expapi\/activities\/course"}},"verb":{"id":"http:\/\/adlnet.gov\/expapi\/verbs\/attempted"},"id":"ed9a911e-6111-4ea6-9d9b-57b881458d8f","authority":{"objectType":"Agent","name":"New Client","mbox":"mailto:hello@learninglocker.net"},"stored":"2017-08-15T18:49:30.351400+00:00","timestamp":"2017-08-15T18:49:30.351400+00:00"}`.' in /var/www/learninglocker/app/locker/repository/Statement/EloquentInserter.php:75
Stack trace:
#0 /var/www/learninglocker/app/locker/repository/Statement/EloquentInserter.php(29): Locker\Repository\Statement\EloquentInserter->compareForConflict(Object(stdClass), Object(stdClass))
#1 /var/www/learninglocker/app/locker/repository/Statement/EloquentStorer.php(38): Locker\Repository\Statement\EloquentInserter->insert(Array, Object(Locker\Repository\Statement\StoreOptions))
#2 /var/www/learninglocker/app/locker/repository/Statement/EloquentRepository.php(31): Locker\Repository\Statement\EloquentStorer->store(Array, Array, Object(Locker\Repository\Statement\StoreOptions))
#3 /var/www/learninglocker/app/controllers/xapi/StatementStoreController.php(144): Locker\Repository\Statement\EloquentRepository->store(Array, Array, Array)
#4 /var/www/learninglocker/app/controllers/xapi/StatementStoreController.php(88): Controllers\xAPI\StatementStoreController->createStatements(Array, Object(Closure))
#5 /var/www/learninglocker/app/controllers/xapi/StatementController.php(63): Controllers\xAPI\StatementStoreController->update(Array)
#6 /var/www/learninglocker/app/controllers/xapi/BaseController.php(44): Controllers\xAPI\StatementController->update()
#7 [internal function]: Controllers\xAPI\BaseController->selectMethod()
#8 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#9 /var/www/learninglocker/bootstrap/compiled.php(3819): Illuminate\Routing\Controller->callAction('selectMethod', Array)
#10 /var/www/learninglocker/bootstrap/compiled.php(3807): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\xAPI\StatementController), Object(Illuminate\Routing\Route), 'selectMethod')
#11 /var/www/learninglocker/bootstrap/compiled.php(3012): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\xAP...', 'selectMethod')
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#13 /var/www/learninglocker/bootstrap/compiled.php(3370): call_user_func_array(Object(Closure), Array)
#14 /var/www/learninglocker/bootstrap/compiled.php(3037): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /var/www/learninglocker/bootstrap/compiled.php(3025): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /var/www/learninglocker/bootstrap/compiled.php(702): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 /var/www/learninglocker/bootstrap/compiled.php(678): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 /var/www/learninglocker/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkLegacyMiddleware.php(20): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/learninglocker/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(51): Clockwork\Support\Laravel\ClockworkLegacyMiddleware->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/learninglocker/bootstrap/compiled.php(5797): Asm89\Stack\Cors->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/learninglocker/bootstrap/compiled.php(6404): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/learninglocker/bootstrap/compiled.php(6351): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/learninglocker/bootstrap/compiled.php(8367): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/learninglocker/bootstrap/compiled.php(639): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#25 /var/www/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run()
#26 {main} [] []
[2018-02-28 18:08:01] local.ERROR: exception 'Locker\Helpers\Exceptions\Conflict' with message 'Conflicts
`{"version":"1.0.0","object":{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id\/5oX4dpMcZUI","definition":{"description":{"und":"great picking"},"name":{"und":"great picking"},"type":"http:\/\/adlnet.gov\/expapi\/activities\/module"}},"actor":{"objectType":"Agent","mbox":"REMOVED","name":"REMOVED"},"context":{"contextActivities":{"parent":[{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id"}],"grouping":[{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id"}]}},"verb":{"id":"http:\/\/adlnet.gov\/expapi\/verbs\/experienced"},"id":"ed9a911e-6111-4ea6-9d9b-57b881458d8f","authority":{"objectType":"Agent","name":"New Client","mbox":"mailto:hello@learninglocker.net"},"stored":"2018-02-28T18:08:01.530700+00:00","timestamp":"2018-02-28T18:08:01.530700+00:00"}`
`{"version":"1.0.0","actor":{"objectType":"Agent","mbox":"REMOVED","name":"REMOED"},"context":{"contextActivities":{"parent":[{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id"}],"grouping":[{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id"}]}},"result":{"completion":false},"object":{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id","definition":{"description":{"und":""},"name":{"und":"DMP Responsiveness Part 2 Value Video"},"type":"http:\/\/adlnet.gov\/expapi\/activities\/course"}},"verb":{"id":"http:\/\/adlnet.gov\/expapi\/verbs\/attempted"},"id":"ed9a911e-6111-4ea6-9d9b-57b881458d8f","authority":{"objectType":"Agent","name":"New Client","mbox":"mailto:hello@learninglocker.net"},"stored":"2017-08-15T18:49:30.351400+00:00","timestamp":"2017-08-15T18:49:30.351400+00:00"}`.' in /var/www/learninglocker/app/locker/repository/Statement/EloquentInserter.php:75
```

**Comment by hallshouse** [comment]
xAPI statements being sent are a result of your Storyline course and are unable to cause Storyline to freeze.
You will need to discuss this issue with either Articulate, your course developer (i.e. are they ruining a script that freezes your browser), or your LMS developer.

**Comment by ht2** [comment]
Hi @mparnelldmp - this is actually an xAPI error. A conflict in xAPI refers to when 2 statements are trying to be inserted with the same "statement.id". This can only happen when the ID is generated client side (otherwise the LRS assigns a unique one). The Activity Provider (Storyline) should be recieving the HTTP 409 conflict response and resending with a freshly generated ID.

**Comment by ht2** [comment]
See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#user-content-2.1.1.s2.b3 for reference.

**Comment by mparnelldmp** [comment]
@hallshouse @ht2 interesting, I'll have to dig into the courses as well as the LMS code we use here as beyond tracking stuff in Learning Locker it's just a friendly frontend for launching courses.

As such I'll have to also get in touch with Articulate.

**Comment by ht2** [comment]
Note in the error, the 2 statements are given to you. Each is different with the same ID: 
```
`{"version":"1.0.0","object":{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id\/5oX4dpMcZUI","definition":{"description":{"und":"great picking"},"name":{"und":"great picking"},"type":"http:\/\/adlnet.gov\/expapi\/activities\/module"}},"actor":{"objectType":"Agent","mbox":"mailto:REMOVED","name":"REMOVED"},"context":{"contextActivities":{"parent":[{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id"}],"grouping":[{"objectType":"Activity","id":"http:\/\/5f3zEt4RD9O_course_id"}]}},"verb":{"id":"http:\/\/adlnet.gov\/expapi\/verbs\/experienced"},"id":"ed9a911e-6111-4ea6-9d9b-57b881458d8f","authority":{"objectType":"Agent","name":"New Client","mbox":"mailto:hello@learninglocker.net"},"stored":"2018-02-28T18:07:55.632200+00:00","timestamp":"2018-02-28T18:07:55.632200+00:00"}`

`{"version":"1.0.0","actor":{"objectType":"Agent","mbox":"REMOVED","name":"REMOVED"},"context":{"contextActivities":{"parent":[{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id"}],"grouping":[{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id"}]}},"result":{"completion":false},"object":{"objectType":"Activity","id":"http:\/\/5iUJiSwmGIg_course_id","definition":{"description":{"und":""},"name":{"und":"DMP Responsiveness Part 2 Value Video"},"type":"http:\/\/adlnet.gov\/expapi\/activities\/course"}},"verb":{"id":"http:\/\/adlnet.gov\/expapi\/verbs\/attempted"},"id":"ed9a911e-6111-4ea6-9d9b-57b881458d8f","authority":{"objectType":"Agent","name":"New Client","mbox":"mailto:hello@learninglocker.net"},"stored":"2017-08-15T18:49:30.351400+00:00","timestamp":"2017-08-15T18:49:30.351400+00:00"}`.'
```

**Comment by mparnelldmp** [comment]
Ah, makes sense. Now the real question is whether or not this is responsible for the courses "freezing" randomly for some users, as we've exhausted every other possibility.
