### ISSUE TITLE
How to import large quantity of statements from another LRS?

### ISSUE THREAD

**Issue by chazwhiz** [LearningLocker/learninglocker#1135]
I am looking at LL as a replacement for another LRS.  I can export all statement data as a CSV or as JSON.  I see LL has no CSV support.  What are my options to get the data in from the JSON file?

I've tried sending it from postman to the */data/xAPI/statements endpoint as a file, but it's an enormous file (~4GB).  I figured I'd need to split it up, which would be fine, except I can't get it small enough to be reasonable OR find the right places to increase file sizes it can accept.  I know it will work in theory, as I can do the POST with a small sample (10 objects in a file), but I need that to scale way up to be practical.  I've set the webapp and xapi .env to use an S3 bucket, and I increased the nginx file size by adding `client_max_body_size 20M;` to `/etc/nginx/nginx.conf` but testing with a ~10MB file still fails.  Below is the response.  I'm guessing there's some other systems that need to be told to accept bigger files?  

`PayloadTooLargeError: request entity too large
    at readStream (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/raw-body/index.js:155:17)
    at getRawBody (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/raw-body/index.js:108:12)
    at read (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/body-parser/lib/types/json.js:134:5)
    at Layer.handle [as handle_request] (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/express/lib/router/index.js:275:10)
    at cors (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/cors/lib/index.js:188:7)
    at /usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/cors/lib/index.js:224:17
    at originCallback (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/cors/lib/index.js:214:15)
    at /usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/cors/lib/index.js:204:7)
    at Layer.handle [as handle_request] (/usr/local/learninglocker/releases/ll-20171010-49196161d59f17908b77833c8cc85b0889cf3e97/xapi/node_modules/express/lib/router/layer.js:95:5)`

**So my specific questions would be either:**

1. **Is there a better way to get the data in?**
2. **If not, what all do I need to change to accept the large JSON file?**

**Version**
2.0.2

**Additional information**
Standard v2 install using Community AMI on AWS.

**Comment by ht2** [comment]
Sounds like you need to write a little script that streams through your JSON file and chunks it into batches of about 1000 statements per request. You can go higher/lower but it comes down to the hardware you're running it on. More statements = more validation per request and a larger bulk write to Mongo. We see good response times with ~1000/batch but have gone up to 10k or even 50k per batch on high end systems. Sorry we can't help more here more - if you're interested in moving this onto an enterprise service however we'd be happy to look at how we could take that data and get it into a paid hosted version.
