### ISSUE TITLE
configuration.url error....

### ISSUE THREAD

**Issue by pexpert9** [LearningLocker/learninglocker#1146]
2018-04-23 14:41:37:956 - ^[[31merror^[[39m:  ValidationError: configuration.url: Path `configuration.url` is required.
    at MongooseError.ValidationError (/usr/local/learninglocker/releases/ll-20180411-74479bb34e1c6be36ba58e0568978040ff025dd7/webapp/node_modules/mongoose/lib/error/validation.js:28:11)
    at model.Document.invalidate (/usr/local/learninglocker/releases/ll-20180411-74479bb34e1c6be36ba58e0568978040ff025dd7/webapp/node_modules/mongoose/lib/document.js:1675:32)
    at /usr/local/learninglocker/releases/ll-20180411-74479bb34e1c6be36ba58e0568978040ff025dd7/webapp/node_modules/mongoose/lib/document.js:1547:17
    at validate (/usr/local/learninglocker/releases/ll-20180411-74479bb34e1c6be36ba58e0568978040ff025dd7/webapp/node_modules/mongoose/lib/schematype.js:784:7)
    at /usr/local/learninglocker/releases/ll-20180411-74479bb34e1c6be36ba58e0568978040ff025dd7/webapp/node_modules/mongoose/lib/schematype.js:829:11
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/usr/local/learninglocker/releases/ll-20180411-74479bb34e1c6be36ba58e0568978040ff025dd7/webapp/node_modules/mongoose/lib/schematype.js:789:19)
    at /usr/local/learninglocker/releases/ll-20180411-74479bb34e1c6be36ba58e0568978040ff025dd7/webapp/node_modules/mongoose/lib/document.js:1545:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by ht2** [comment]
Please conform to our issue template.
