### ISSUE TITLE
Unauthorised at_default

### ISSUE THREAD

**Issue by caperneoignis** [LearningLocker/learninglocker#1169]
**Version**
AMI with version 2.1.2 on it. 

Not sure how to reproduce, unsure if it was because I accidentally had two sessions going in the same browser or if it is something else. But this is the error I'm getting.

API > 2018-05-17 15:05:10:328 - error: Auth error:  
API > { message: 'Unauthorised', 
API >   name: '_default',                                                                                                      
API >   stack: 'Error: Unauthorised\n 
   at _default (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/api/dist/server/webpack:/tmp/learninglocker/webapp/lib/errors/BaseError.js:5:18)\n 
   at new  _default (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/api/dist/server/webpack:/tmp/learninglocker/webapp/lib/errors/Unauthorised.js:4:17)\n 
   at Strategy._callee2$ (/usr/local/learninglocker/releases/ll-201801091b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/api/dist/server/webpack:/auth/passport.js:84:13)\n 
   at tryCatch (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:65:40)\n
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:303:22)\n 
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/regenerator-runtime/runtime.js:117:21)\n
    at step (/usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)\n 
   at /usr/local/learninglocker/releases/ll-20180109-1b4f9d8187af4af21ca098e9e5daa3332fccae33/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13' }

**Expected behaviour**
To not throw up an unauthorized notice, and then proceed to process as expected. Either kick me out, or present to me a longer lasting notice then a disappearing red banner that appears and vaporizes before I can read it fully. The other expected behavior, if this is the case of doing two sessions at once, is to log out one of the sessions or just automatically let me in to the other session.

**Actual behaviour**
Notices appear then disappear about unauthorized access for admin. Then allows me to continue.

**Additional information**
OS: AMI with version 2.1.2
Browser: Chrome version  66.0.3359.139

**Comment by ht2** [comment]
Hi, I would recommending upgrading your instance as it seems to be far behind the current version (2.3).

**Comment by caperneoignis** [comment]
I upgraded, and I'm still getting the error, but now the error is staying on the page. ```<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Internal Server Error</pre> </body> </html>```

So what would cause this? I'm running 2.3.3 for the webapp.

**Comment by caperneoignis** [comment]
Yes, I upgraded and used migration step for the remote mongodb that LL is currently using. Let me get a better print out.

**Comment by caperneoignis** [comment]
```
Error: Unauthorised
0|API      |     at _default (/usr/local/learninglocker/releases/ll-20180517-a1885ca830b97b65f1c333f9a0c4e31d09e29b38/webapp/api/dist/server/webpack:/tmp/learninglocker/webapp/lib/errors/BaseError.js:5:18)
0|API      |     at new _default (/usr/local/learninglocker/releases/ll-20180517-a1885ca830b97b65f1c333f9a0c4e31d09e29b38/webapp/api/dist/server/webpack:/tmp/learninglocker/webapp/lib/errors/Unauthorised.js:4:17)
0|API      |     at Strategy._callee2$ (/usr/local/learninglocker/releases/ll-20180517-a1885ca830b97b65f1c333f9a0c4e31d09e29b38/webapp/api/dist/server/webpack:/auth/passport.js:91:13)
0|API      |     at tryCatch (/usr/local/learninglocker/releases/ll-20180517-a1885ca830b97b65f1c333f9a0c4e31d09e29b38/webapp/node_modules/regenerator-runtime/runtime.js:65:40)
0|API      |     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/learninglocker/releases/ll-20180517-a1885ca830b97b65f1c333f9a0c4e31d09e29b38/webapp/node_modules/regenerator-runtime/runtime.js:303:22)
0|API      |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/learninglocker/releases/ll-20180517-a1885ca830b97b65f1c333f9a0c4e31d09e29b38/webapp/node_modules/regenerator-runtime/runtime.js:117:21)
0|API      |     at step (/usr/local/learninglocker/releases/ll-20180517-a1885ca830b97b65f1c333f9a0c4e31d09e29b38/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
0|API      |     at /usr/local/learninglocker/releases/ll-20180517-a1885ca830b97b65f1c333f9a0c4e31d09e29b38/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```
I'm also getting one for the storage, but I figured that out, it was because the old version stored the state in Mongo and the new version does file storage. So that is an easy one to get around.

**Comment by caperneoignis** [comment]
Let me try incog and I'll let you know.

**Comment by caperneoignis** [comment]
I see this in the browser, when I was about to start incog, ```/api/connection/statement?filter=%7B%7D&sort=%7B"timestamp"%3A-1%2C"_id"%3A1%7D```

**Comment by caperneoignis** [comment]
I'm not seeing it now, not sure if it fixed it self or what is going on. But nothing came up in incognito.

**Comment by ryansmith94** [comment]
Closing due to inactivity.

**Comment by caperneoignis** [comment]
Yes, go ahead, I have not been able to reproduce after the update. I think what happened was I was using an older version and the new version corrected that issue. The redis server might also not been setup correctly so session information was being dropped. Any number of issues might have been taking place that no longer take place.

**Comment by ryansmith94** [comment]
Ok cool thanks @caperneoignis 👍
