### ISSUE TITLE
QUEUE ERROR: 'Redis version needs to be greater than 2.8.18. Current: 2.8.17'

### ISSUE THREAD

**Issue by doender** [LearningLocker/learninglocker#1284]
We're seeing the following error in version 2.6.1:

```
'Error: Redis version needs to be greater than 2.8.18. Current: 2.8.17
 at /usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bull/lib/queue.js:187:13\n    at tryCatcher (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/promise.js:512:31)
 at Promise._settlePromise (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/promise.js:569:18)
 at Promise._settlePromise0 (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/promise.js:614:10)
 at Promise._settlePromises (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/promise.js:694:18)
 at _drainQueueStep (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/async.js:138:12)
 at _drainQueue (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/async.js:147:5)
  at Immediate.Async.drainQueues (/usr/local/learninglocker/releases/ll-20181128-f4fd50090b44b0b37fcd23c5f664619ee5c0e279/webapp/node_modules/bluebird/js/release/async.js:17:14)
 at Immediate.args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)
at processImmediate [as _immediateCallback] (timers.js:745:5)'
```

**Comment by ryansmith94** [comment]
@ht2 any thoughts on this?

**Comment by ht2** [comment]
Yea, looks pretty self explanatory. The Redis queue driver seems like it needs v2.8.18 of Redis, you are using 2.8.17.

Looking at [our lock](https://github.com/LearningLocker/learninglocker/blob/master/yarn.lock#L2163) we are using 3.4.8 of Bull, which says this in its documentation: https://github.com/OptimalBits/bull/tree/v3.4.8#install

I've updated our [installation docs](https://github.com/LearningLocker/docs/blob/master/src/guides-custom-installation.md#requirements) accordingly.

**Comment by ryansmith94** [comment]
Nice thanks James 👍
