### ISSUE TITLE
issue when doing migrate on version 20181217

### ISSUE THREAD

**Issue by caperneoignis** [LearningLocker/learninglocker#1286]
**Version**
using deploy.sh script, ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7

**Steps to reproduce the bug**
1. upgrade to newest version and run yarn migrate

**Expected behaviour**
no errors just migrate the data.

**Actual behaviour**
````
error: uncaughtException: Module version mismatch. Expected 48, got 57.
{ date: 'Mon Dec 17 2018 19:48:44 GMT+0000 (UTC)',
  process:
   { pid: 15566,
     uid: 999,
     gid: 999,
     cwd: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp',
     execPath: '/usr/local/learninglocker/releases/.nvm/versions/node/v6.15.1/bin/node',
     version: 'v6.15.1',
     argv:
      [ '/usr/local/learninglocker/releases/.nvm/versions/node/v6.15.1/bin/node',
        '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server',
        'migrateMongo',
        '--up' ],
     memoryUsage:
      { rss: 118452224,
        heapTotal: 92971008,
        heapUsed: 65273312,
        external: 36104940 } },
  os:
   { loadavg: [ 0.21875, 0.4072265625, 0.26513671875 ],
     uptime: 98043 },
  trace:
   [ { column: null,
       file: null,
       function: 'Error',
       line: null,
       method: null,
       native: true },
     { column: 18,
       file: 'module.js',
       function: 'Module._extensions..node',
       line: 604,
       method: '.node',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 494,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 453,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Module._load',
       line: 445,
       method: '_load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 504,
       method: 'require',
       native: false },
     { column: 19,
       file: 'internal/module.js',
       function: 'require',
       line: 20,
       method: null,
       native: false },
     { column: 16,
       file: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/bcrypt/bcrypt.js',
       function: null,
       line: 6,
       method: null,
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module._compile',
       line: 577,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Module._extensions..js',
       line: 586,
       method: '.js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 494,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 453,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Module._load',
       line: 445,
       method: '_load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 504,
       method: 'require',
       native: false },
     { column: 19,
       file: 'internal/module.js',
       function: 'require',
       line: 20,
       method: null,
       native: false },
     { column: 1,
       file: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/external "bcrypt"',
       function: 'Object.module.exports.Object.defineProperty.value',
       line: 1,
       method: 'value',
       native: false },
     { column: 1,
       file: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/webpack/bootstrap b3050399100addd0e2ba',
       function: '__webpack_require__',
       line: 19,
       method: null,
       native: false },
     { column: 1,
       file: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/tmp/learninglocker/webapp/lib/models/user.js',
       function: 'Object.module.exports.Object.defineProperty.value',
       line: 9,
       method: 'value',
       native: false },
     { column: 1,
       file: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/webpack/bootstrap b3050399100addd0e2ba',
       function: '__webpack_require__',
       line: 19,
       method: null,
       native: false },
     { column: 1,
       file: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/commands/createSiteAdmin.js',
       function: null,
       line: 3,
       method: null,
       native: false },
     { column: 1,
       file: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/webpack/bootstrap b3050399100addd0e2ba',
       function: '__webpack_require__',
       line: 19,
       method: null,
       native: false },
     { column: 1,
       file: '/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/server.js',
       function: null,
       line: 4,
       method: null,
       native: false } ],
  stack:
   [ 'Error: Module version mismatch. Expected 48, got 57.',
     '    at Error (native)',
     '    at Object.Module._extensions..node (module.js:604:18)',
     '    at Module.load (module.js:494:32)',
     '    at tryModuleLoad (module.js:453:12)',
     '    at Function.Module._load (module.js:445:3)',
     '    at Module.require (module.js:504:17)',
     '    at require (internal/module.js:20:19)',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/bcrypt/bcrypt.js:6:16)',
     '    at Module._compile (module.js:577:32)',
     '    at Object.Module._extensions..js (module.js:586:10)',
     '    at Module.load (module.js:494:32)',
     '    at tryModuleLoad (module.js:453:12)',
     '    at Function.Module._load (module.js:445:3)',
     '    at Module.require (module.js:504:17)',
     '    at require (internal/module.js:20:19)',
     '    at Object.module.exports.Object.defineProperty.value (/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/external "bcrypt":1:1)',
     '    at __webpack_require__ (/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/webpack/bootstrap b3050399100addd0e2ba:19:1)',
     '    at Object.module.exports.Object.defineProperty.value (/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/tmp/learninglocker/webapp/lib/models/user.js:9:1)',
     '    at __webpack_require__ (/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/webpack/bootstrap b3050399100addd0e2ba:19:1)',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/commands/createSiteAdmin.js:3:1)',
     '    at __webpack_require__ (/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/webpack/bootstrap b3050399100addd0e2ba:19:1)',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20181217-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/server.js:4:1)' ] }
(node:15566) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:15566) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
````

**Additional information**
OS: ubuntu 18 using nvm to get node v6 since ubuntu 18 is using node 8
Browser: n/a

**Comment by caperneoignis** [comment]
I have let it run for about 30 minutes now and it hasn't moved from that error. Is there some sort of progress bar or status be displayed? how will I know it is done?

**Comment by ryansmith94** [comment]
@ht2 you able to triage this? @caperneoignis you should be fine to use Node 8 btw.

**Comment by ht2** [comment]
You need to delete your node_modules and rerun yarn install. One of the packages is complaining on the Node version change.

We'll have to look into Node 10, but I haven't got a firm answer for you right now.

**Comment by caperneoignis** [comment]
Gotcha.

**Comment by caperneoignis** [comment]
So this is what happens when running with node8 and newest version of LL using deploy.sh script and doing node cli/dist/server migrateMongo-u

````
(node:10339) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:10339) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Error: Db migration (20171008104700_personas_indexes) does not match (20171122100800_common_indexes)
    at /usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/migrateMongo/index.js:97:13
    at List.__iterate (/usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/immutable/dist/immutable.js:2206:13)
    at List.forEach (/usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/immutable/dist/immutable.js:4381:19)
    at _callee2$ (/usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/cli/dist/server/webpack:/migrateMongo/index.js:92:17)
    at tryCatch (/usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/learninglocker/releases/ll-20181218-7894ed0792e96941a3193ab057e35f9ba083a5b7/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
````

**Comment by caperneoignis** [comment]
seem to be getting a migration error and I'm not sure why.  
what it looks like when I run the "node cli/dist/server/ migrateMongo -i" command
longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
2018-12-18 17:13:04:934 - info: Last run migration:  20180212_expiration
2018-12-18 17:13:04:964 - info: Outstanding migrations:
                20180320093000_shareable_dashboards
