### ISSUE TITLE
Open Source v6.2.4 build failure for grpc_node module

### ISSUE THREAD

**Issue by jbeninson** [LearningLocker/learninglocker#1535]
#### What version were you using?
Open Source v6.2.4
Debian 10
node 10

#### What is the actual behaviour?
The build for (Open Source) v6.2.4 is failing due to a dependency on grpc.
 
#### Dockerfile
```
FROM debian:10

RUN apt-get update \
  && apt-get install -y curl git python build-essential xvfb \
  apt-transport-https \
  wget \
  procps \
  unzip \
  gettext-base \
  && wget -qO- https://deb.nodesource.com/setup_10.x | bash \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/* \ 
  apt-get clean

RUN npm install -g yarn

RUN git clone https://github.com/LearningLocker/learninglocker.git /opt/learninglocker \
  && cd /opt/learninglocker \
  && git checkout v6.2.4 \
  && yarn install --ignore-engines \
  && yarn build-all
```

#### What is the expected behavior?
It fails when installing gRPC. There is a quite sizable error output but here is the last few lines. 
```
cc1plus: all warnings being treated as errors
make: *** [grpc.target.mk:396: Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/flow_control.o] Error 1
make: Leaving directory '/opt/learninglocker/node_modules/google-gax/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/learninglocker/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/bin/node" "/opt/learninglocker/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/opt/learninglocker/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/opt/learninglocker/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /opt/learninglocker/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```

#### Is there any additional information that will help us replicate/understand the problem?
execute `docker build -t ll_bug_report .`
it still succeeds when using node8

**Comment by AodhanLP** [comment]
Hey @jbeninson , were you able to resolve this issue?

**Comment by AodhanLP** [comment]
Hey @jbeninson , I see you closed this issue. I believe I'm facing the same problem, have you any advice/solutions on how to fix this? Thanks.
