### ISSUE TITLE
Upgrading from 6.2.3 > 7.0.0 - yarn migrate error

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#1551]
#### What version were you using?
OSS 6.2.3 > 7.0.0

#### What steps can we follow to reproduce the behaviour?
Upgrade via deploy.sh script.

#### What is the actual behaviour?
Can't log in after the upgrade.
Failure message in installation for 'yarn migrate'.
```
(node:1221) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Error: Db migration (20171121153300_update_refs) does not match (20171122100800_common_indexes)
    at /usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/cli/dist/server/webpack:/migrateMongo/index.js:125:13
    at List.__iterate (/usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/node_modules/immutable/dist/immutable.js:2206:13)
    at List.forEach (/usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/node_modules/immutable/dist/immutable.js:4381:19)
    at _callee3$ (/usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/cli/dist/server/webpack:/migrateMongo/index.js:120:17)
    at tryCatch (/usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/learninglocker/releases/ll-20200727-bec94daa7bd602a4752ca570db03b13e9c02d037/webapp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
Done in 2.87s.
```
The same message appears when trying to manually run 'yarn migrate' in webapp.

#### What is the expected behavior?
Upgrade completes with no errors in migration and I can log in.

#### Is there any additional information that will help us replicate/understand the problem?
DB is on MongoAtlas v4.2.8
Redis is Elasticache

**Comment by davidpesce** [comment]
A bit more info from yarn:
```
2020-07-27 21:33:41:618 - info: Last run migration:  20190719000000_migrate_viz_types_of_templates
2020-07-27 21:33:41:803 - info: Outstanding migrations:
		20200227000000_rename_curatr_vis_tpl_types_to_stream
		20200228000000_rename_curatr_dashboards_to_stream
```

**Comment by ryansmith94** [comment]
Hey @davidpesce, this might be related to #1524.

**Comment by davidpesce** [comment]
Worked like a charm! Thanks, @ryansmith94!!
