### ISSUE TITLE
Adding administrator and organisation fails with fresh install of Learning Locker on Ubuntu Server 20.04.1

### ISSUE THREAD

**Issue by agrohn** [LearningLocker/learninglocker#1565]
#### What version were you using?

Open Source

#### What steps can we follow to reproduce the behaviour?

1. Create a fresh install of Ubuntu Server 20.04.1
2. Login and install learning locker via cli (with fixed deployll.sh that takes nodejs/node executables properly into account)
3. Attempt to add new organisation and administrator via cli.

#### What is the actual behaviour?

```bash
# node cli/dist/server createSiteAdmin YOUR.EMAIL@ADDRESS.COM ORGANISATION_NAME YOUR_PASSWORD
2020-11-16 09:28:12:905 - error: uncaughtException: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node' 
{ date:
   'Mon Nov 16 2020 09:28:12 GMT+0000 (Coordinated Universal Time)',
  process:
   { pid: 84537,
     uid: 0,
     gid: 0,
     cwd:
      '/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp',
     execPath: '/usr/bin/node',
     version: 'v10.23.0',
     argv:
      [ '/usr/bin/node',
        '/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/cli/dist/server',
        'createSiteAdmin',
        'YOUR.EMAIL@ADDRESS.COM',
        'ORGANISATION_NAME',
        'YOUR_PASSWORD' ],
     memoryUsage:
      { rss: 133328896,
        heapTotal: 97812480,
        heapUsed: 66989152,
        external: 36994220 } },
  os:
   { loadavg: [ 0.17822265625, 0.43701171875, 0.47412109375 ],
     uptime: 1952 },
  trace:
   [ { column: 17,
       file:
        '/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/google-gax/node_modules/grpc/src/grpc_extension.js',
       function: null,
       line: 43,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 778,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 789,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 692,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 25,
       method: null,
       native: false },
     { column: 12,
       file:
        '/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/google-gax/node_modules/grpc/src/client.js',
       function: null,
       line: 37,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 778,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 789,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 692,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 25,
       method: null,
       native: false },
     { column: 14,
       file:
        '/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/google-gax/node_modules/grpc/index.js',
       function: null,
       line: 30,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 778,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 789,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false } ],
  stack:
   [ 'Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"',
     'Original error: Cannot find module \'/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node\'',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/google-gax/node_modules/grpc/src/grpc_extension.js:43:17)',
     '    at Module._compile (internal/modules/cjs/loader.js:778:30)',
     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)',
     '    at Module.load (internal/modules/cjs/loader.js:653:32)',
     '    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)',
     '    at Function.Module._load (internal/modules/cjs/loader.js:585:3)',
     '    at Module.require (internal/modules/cjs/loader.js:692:17)',
     '    at require (internal/modules/cjs/helpers.js:25:18)',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/google-gax/node_modules/grpc/src/client.js:37:12)',
     '    at Module._compile (internal/modules/cjs/loader.js:778:30)',
     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)',
     '    at Module.load (internal/modules/cjs/loader.js:653:32)',
     '    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)',
     '    at Function.Module._load (internal/modules/cjs/loader.js:585:3)',
     '    at Module.require (internal/modules/cjs/loader.js:692:17)',
     '    at require (internal/modules/cjs/helpers.js:25:18)',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/google-gax/node_modules/grpc/index.js:30:14)',
     '    at Module._compile (internal/modules/cjs/loader.js:778:30)',
     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)',
     '    at Module.load (internal/modules/cjs/loader.js:653:32)',
     '    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)',
     '    at Function.Module._load (internal/modules/cjs/loader.js:585:3)' ] }
(node:84537) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
{ MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:198:13)
    at Pool.EventEmitter.emit (domain.js:448:20)
    at createConnection (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:571:14)
    at connect (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:994:11)
    at makeConnection (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {} }
Unhandled rejection MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:198:13)
    at Pool.EventEmitter.emit (domain.js:448:20)
    at createConnection (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:571:14)
    at connect (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:994:11)
    at makeConnection (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/usr/local/learninglocker/releases/ll-20201116-594ef496d8a9411340404301a55cf95de0079a6d/webapp/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

#### What is the expected behavior?

1. Create a fresh install of Ubuntu Server 20.04.1
2. Login and install learning locker via cli (with fixed deployll.sh that takes nodejs/node executables properly into account)
3. Attempt to add new organisation and administrator via cli.
4. Organization and adminstrator are added to learning locker.

#### Is there any additional information that will help us replicate/understand the problem?

`/var/log/learninglocker/install.log`  shows that gprc module in questions fails to build:

```
...
make: Entering directory '/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_factory.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/message_compress.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_gzip.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_identity.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/format_request.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/httpcli.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/parser.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/call_combiner.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/combiner.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_epoll1_linux.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_epollex_linux.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_epollsig_linux.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_poll_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/exec_ctx.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/executor.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/fork_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/fork_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/gethostname_fallback.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/gethostname_host_name_max.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/gethostname_sysconf.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iocp_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/is_epollexclusive_available.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/load_file.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/lockfree_event.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/network_status_tracker.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/polling_entity.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resource_quota.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/sockaddr_utils.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_factory_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_mutator.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_common_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_linux.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_client_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_client_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_client_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_utils_posix_ifaddrs.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_utils_posix_noifaddrs.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/time_averaged_stats.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_generic.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_heap.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_manager.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/udp_server.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/unix_sockets_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/unix_sockets_posix_noop.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_cv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_eventfd.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_nospecial.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_pipe.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/json/json.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/json/json_reader.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/json/json_string.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/json/json_writer.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/b64.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/percent_encoding.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice_buffer.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice_hash_table.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice_intern.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice_string_helpers.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/alarm.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/api_trace.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/byte_buffer.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/byte_buffer_reader.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/call.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/call_details.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/call_log_batch.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/channel.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/channel_init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/channel_ping.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/channel_stack_type.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/completion_queue.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/completion_queue_factory.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/event_string.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/lame_client.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/metadata_array.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/server.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/validate_metadata.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/version.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/bdp_estimator.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/byte_stream.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/connectivity_state.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/error_utils.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/metadata.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/metadata_batch.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/pid_controller.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/service_config.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/static_metadata.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/status_conversion.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/timeout_encoding.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/transport.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/transport_op_string.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/trace.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/bin_decoder.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/bin_encoder.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_plugin.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/flow_control.o
../deps/grpc/src/core/ext/transport/chttp2/transport/flow_control.cc: In member function ‘virtual uint32_t grpc_core::chttp2::TransportFlowControl::MaybeSendUpdate(bool)’:
../deps/grpc/src/core/ext/transport/chttp2/transport/flow_control.cc:188:74: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
  188 |   const uint32_t target_announced_window = (const uint32_t)target_window();
      |                                                                          ^
cc1plus: all warnings being treated as errors
make: *** [grpc.target.mk:396: Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/flow_control.o] Error 1
make: Leaving directory '/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/learninglocker/webapp/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/learninglocker/webapp/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/bin/node" "/tmp/learninglocker/webapp/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v10.23.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /tmp/learninglocker/webapp/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.4.0-42-generic
node-pre-gyp ERR! command "/usr/bin/node" "/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v10.23.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /tmp/learninglocker/webapp/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/tmp/learninglocker/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
done!
```

**Comment by dandunckelman** [comment]
@agrohn try the fix from https://github.com/LearningLocker/learninglocker/pull/1600

**Comment by agrohn** [comment]
@dandunckelman Alrighty, I'll give it a go soon.

**Comment by agrohn** [comment]
@dandunckelman After applying that PR, installation is working as expected. :+1:

**Comment by changWEit** [comment]
> @dandunckelman应用该 PR 后，安装按预期进行。👍

What does it mean? Don't understand how to solve the problem?

**Comment by changWEit** [comment]
> @agrohn[从#1600](https://github.com/LearningLocker/learninglocker/pull/1600)尝试修复[](https://github.com/LearningLocker/learninglocker/pull/1600)

linux installation, how to do it.
