### ISSUE TITLE
error: uncaughtException: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"

### ISSUE THREAD

**Issue by cvanderlinden** [LearningLocker/learninglocker#1601]
`[LL] Attempting to create your site admin. If this step fails, then it is possible Mongo has not started.
[LL] Attempt to manually start the Mongo service and then run this command:
[LL] cd /usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80; node cli/dist/server createSiteAdmin YOUR.EMAIL@ADDRESS.COM ORGANISATION_NAME YOUR_PASSWORD
2021-11-09 00:43:41:171 - error: uncaughtException: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'
{ date:
   'Tue Nov 09 2021 00:43:41 GMT+0000 (Coordinated Universal Time)',
  process:
   { pid: 101429,
     uid: 0,
     gid: 0,
     cwd:
      '/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp',
     execPath: '/usr/bin/node',
     version: 'v10.24.1',
     argv:
      [ '/usr/bin/node',
        '/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/cli/dist/server',
        'createSiteAdmin',
        'email@email.com',
        'Org-Name',
        'passwordgoeshere' ],
     memoryUsage:
      { rss: 130473984,
        heapTotal: 95715328,
        heapUsed: 59285800,
        external: 36192664 } },
  os:
   { loadavg: [ 0.00146484375, 0.3994140625, 0.68408203125 ],
     uptime: 20261 },
  trace:
   [ { column: 17,
       file:
        '/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/node_modules/google-gax/node_modules/grpc/src/grpc_extension.js',
       function: null,
       line: 43,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 778,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 789,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 692,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 25,
       method: null,
       native: false },
     { column: 12,
       file:
        '/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/node_modules/google-gax/node_modules/grpc/src/client.js',
       function: null,
       line: 37,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 778,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 789,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 692,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 25,
       method: null,
       native: false },
     { column: 14,
       file:
        '/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/node_modules/google-gax/node_modules/grpc/index.js',
       function: null,
       line: 30,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 778,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 789,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false } ],
  stack:
   [ 'Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"',
     'Original error: Cannot find module \'/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node\'',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/node_modules/google-gax/node_modules/grpc/src/grpc_extension.js:43:17)',
     '    at Module._compile (internal/modules/cjs/loader.js:778:30)',
     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)',
     '    at Module.load (internal/modules/cjs/loader.js:653:32)',
     '    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)',
     '    at Function.Module._load (internal/modules/cjs/loader.js:585:3)',
     '    at Module.require (internal/modules/cjs/loader.js:692:17)',
     '    at require (internal/modules/cjs/helpers.js:25:18)',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/node_modules/google-gax/node_modules/grpc/src/client.js:37:12)',
     '    at Module._compile (internal/modules/cjs/loader.js:778:30)',
     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)',
     '    at Module.load (internal/modules/cjs/loader.js:653:32)',
     '    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)',
     '    at Function.Module._load (internal/modules/cjs/loader.js:585:3)',
     '    at Module.require (internal/modules/cjs/loader.js:692:17)',
     '    at require (internal/modules/cjs/helpers.js:25:18)',
     '    at Object.<anonymous> (/usr/local/learninglocker/releases/ll-20211109-ac0803ea165dd49ad74e059a294f5635708d3b80/webapp/node_modules/google-gax/node_modules/grpc/index.js:30:14)',
     '    at Module._compile (internal/modules/cjs/loader.js:778:30)',
     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)',
     '    at Module.load (internal/modules/cjs/loader.js:653:32)',
     '    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)',
     '    at Function.Module._load (internal/modules/cjs/loader.js:585:3)' ] }
(node:101429) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

**Comment by cvanderlinden** [comment]
Also when trying to run `yarn install` manually I get

> error @azure/logger@1.0.3: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.24.1"

**Comment by cvanderlinden** [comment]
Trying to run `npm install` manually I get

> node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@10.24.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@10.24.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)

**Comment by dandunckelman** [comment]
@cvanderlinden try the fix from https://github.com/LearningLocker/learninglocker/pull/1600

**Comment by cvanderlinden** [comment]
@dandunckelman I switched from Ubuntu 20.04 to Ubuntu 18.04 and I was able to resolve the issue that way, sorry not able to help test at this moment.

**Comment by dandunckelman** [comment]
@cvanderlinden Right, I've heard that's a workaround.

It's currently working in 20.04. I was just passing that on to follow up on the issue. No need to test.
