### ISSUE TITLE
Response of 500 from GET /data/xAPI/statements/ with statementId parameter only

### ISSUE THREAD

**Issue by paulnebel** [LearningLocker/learninglocker#475]
I've just installed the latest tagged release of LearningLocker (v1.2.1-beta) in order to solve the issue reported by ztraboo as issue #413.  Just like him I'm trying to send a request to my instance at 
/data/xAPI/statements?statementId={my statement id} only now, instead of getting a 400 response telling me that 'When using statementId or voidedStatementId, the only other                                                         parameters allowed are attachments and\\/or format.' I get a 500 error:

```
{
    error: true
    message: "Undefined variable: id"
    code: 500
    trace: "#0 /var/www/learninglocker/app/controllers/xapi/StatementController.php(191): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/learni...', 191, Array) #1 /var/www/learninglocker/app/controllers/xapi/BaseController.php(38): Controllers\xAPI\StatementController->show() #2 [internal function]: Controllers\xAPI\BaseController->selectMethod() #3 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array) #4 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('selectMethod', Array) #5 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\xAPI\StatementController), Object(Illuminate\Routing\Route), 'selectMethod') #6 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\xAP...', 'selectMethod') #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #8 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array) #9 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #11 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true) #14 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true) #15 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true) #16 /var/www/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true) #17 /var/www/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #18 /var/www/learninglocker/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main}"
}
```

My understanding was that this issue was fixed, but it appears to be worse.

**Comment by ryansmith94** [comment]
Thanks for reporting the issue. This is already fixed in the issue/conformance branch, however that branch is very much a development branch and should be used with caution.
