### ISSUE TITLE
404 when using TC Statement Generator

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#496]
I'm getting the following error when using the TinCan Statement Generator ().

```
"error": true,
"message": "",
"code": 404,
"trace": "#0 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1049): Illuminate\\Routing\\RouteCollection->match(Object(Illuminate\\Http\\Request))\ #1 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1017): Illuminate\\Routing\\Router->findRoute(Object(Illuminate\\Http\\Request))\ #2 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(996): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\ #3 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(776): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\ #4 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(746): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\ #5 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\ #6 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\ #7 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\ #8 \/var\/www\/learninglocker\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\ #9 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(642): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\ #10 \/var\/www\/learninglocker\/public\/index.php(49): Illuminate\\Foundation\\Application->run()\ #11 {main}"
```

I'm guessing this is something with my configuration, but cannot figure it out. I've also used Postman to attempt sending data to the endpoint with no success.
Using LL 1.3.0

**Comment by davidpesce** [comment]
Turns out it is the trailing slash in the endpoint. Remove that and it works fine!
