### ISSUE TITLE
setUser() must implement interface Illuminate\\Auth\\UserInterface, null given

### ISSUE THREAD

**Issue by FrankTrog** [LearningLocker/learninglocker#820]
**Version**
develop at 97ebfc7dca33829a21627908e9c9becc08599c30 on 1.12.1 

**Steps to reproduce the bug**
Not sure it would be easy to reproduce on another system due to all of the parts and pieces involved with setup/install. 
1. Download and modify Tin Can xAPI library for php and/or javascript. You could also use the sample test file in TinCanPHP-master/sample/index.php.
2. Input credentials and attempt to run a set/push and/or retrieve statement. Error occurs. Error is listed below.

setUser() must implement interface Illuminate\\Auth\\UserInterface, null given

**Expected behaviour**
Should be able to set/push and retrieve statements from the lRS>

**Actual behaviour**
Feature is throwing an error regarding setUser and the UserIntreface. 

**Additional information**
OS: Windows 10 Home 64 bit
Browser: Chrome 50.0.2661.102 m
MongoDB 3.2 64bit
Xampp 3.2.2

Please let me know what else I can provide to help. 

Error from retrieve, I (think).
TinCan\LRSResponse Object ( [success] => [content] => {"error":true,"success":false,"message":"Argument 1 passed to Illuminate\\Auth\\Guard::setUser() must implement interface Illuminate\\Auth\\UserInterface, null given, called in D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Guard.php on line 482 and defined","code":500,"trace":"#0 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Guard.php(682): Illuminate\\Exception\\Handler->handleError(4096, 'Argument 1 pass...', 'D:\\\\xampp\\\\htdocs...', 682, Array)\n#1 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Guard.php(482): Illuminate\\Auth\\Guard->setUser(NULL)\n#2 [internal function]: Illuminate\\Auth\\Guard->onceUsingId(Object(MongoId))\n#3 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php(138): call_user_func_array(Array, Array)\n#4 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(208): Illuminate\\Support\\Manager->__call('onceUsingId', Array)\n#5 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(208): Illuminate\\Auth\\AuthManager->onceUsingId(Object(MongoId))\n#6 D:\\xampp\\htdocs\\learninglocker\\app\\filters.php(72): Illuminate\\Support\\Facades\\Facade::__callStatic('onceUsingId', Array)\n#7 D:\\xampp\\htdocs\\learninglocker\\app\\filters.php(72): Illuminate\\Support\\Facades\\Auth::onceUsingId(Object(MongoId))\n#8 [internal function]: {closure}(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#9 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(199): call_user_func_array(Object(Closure), Array)\n#10 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(154): Illuminate\\Events\\Dispatcher->fire('router.filter: ...', Array, true)\n#11 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1473): Illuminate\\Events\\Dispatcher->until('router.filter: ...', Array)\n#12 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1435): Illuminate\\Routing\\Router->callRouteFilter('auth.statement', Array, Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#13 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1322): Illuminate\\Routing\\Router->callAttachedBefores(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#14 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1029): Illuminate\\Routing\\Router->callRouteBefore(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#15 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#16 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(775): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#17 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#18 D:\\xampp\\htdocs\\learninglocker\\vendor\\itsgoingd\\clockwork\\Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware.php(20): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#19 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware.php(72): Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#20 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 D:\\xampp\\htdocs\\learninglocker\\vendor\\stack\\builder\\src\\Stack\\StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#23 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#24 D:\\xampp\\htdocs\\learninglocker\\public\\index.php(49): Illuminate\\Foundation\\Application->run()\n#25 {main}"} [httpResponse] => Array ( [status] => 500 [headers] => Array ( [contentType] => application/json [date] => Mon, 30 May 2016 03:19:41 GMT ) [_content] => {"error":true,"success":false,"message":"Argument 1 passed to Illuminate\\Auth\\Guard::setUser() must implement interface Illuminate\\Auth\\UserInterface, null given, called in D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Guard.php on line 482 and defined","code":500,"trace":"#0 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Guard.php(682): Illuminate\\Exception\\Handler->handleError(4096, 'Argument 1 pass...', 'D:\\\\xampp\\\\htdocs...', 682, Array)\n#1 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Guard.php(482): Illuminate\\Auth\\Guard->setUser(NULL)\n#2 [internal function]: Illuminate\\Auth\\Guard->onceUsingId(Object(MongoId))\n#3 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php(138): call_user_func_array(Array, Array)\n#4 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(208): Illuminate\\Support\\Manager->__call('onceUsingId', Array)\n#5 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(208): Illuminate\\Auth\\AuthManager->onceUsingId(Object(MongoId))\n#6 D:\\xampp\\htdocs\\learninglocker\\app\\filters.php(72): Illuminate\\Support\\Facades\\Facade::__callStatic('onceUsingId', Array)\n#7 D:\\xampp\\htdocs\\learninglocker\\app\\filters.php(72): Illuminate\\Support\\Facades\\Auth::onceUsingId(Object(MongoId))\n#8 [internal function]: {closure}(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#9 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(199): call_user_func_array(Object(Closure), Array)\n#10 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(154): Illuminate\\Events\\Dispatcher->fire('router.filter: ...', Array, true)\n#11 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1473): Illuminate\\Events\\Dispatcher->until('router.filter: ...', Array)\n#12 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1435): Illuminate\\Routing\\Router->callRouteFilter('auth.statement', Array, Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#13 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1322): Illuminate\\Routing\\Router->callAttachedBefores(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#14 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1029): Illuminate\\Routing\\Router->callRouteBefore(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#15 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#16 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(775): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#17 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#18 D:\\xampp\\htdocs\\learninglocker\\vendor\\itsgoingd\\clockwork\\Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware.php(20): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#19 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware.php(72): Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#20 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 D:\\xampp\\htdocs\\learninglocker\\vendor\\stack\\builder\\src\\Stack\\StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#23 D:\\xampp\\htdocs\\learninglocker\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#24 D:\\xampp\\htdocs\\learninglocker\\public\\index.php(49): Illuminate\\Foundation\\Application->run()\n#25 {main}"} [_metadata] => Array ( [timed_out] => [blocked] => 1 [eof] => [wrapper_data] => Array ( [0] => HTTP/1.0 500 Internal Server Error [1] => Date: Mon, 30 May 2016 03:19:41 GMT [2] => Server: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.20 [3] => Vary: Authorization [4] => X-Powered-By: PHP/5.6.20 [5] => Cache-Control: private, must-revalidate [6] => pragma: no-cache [7] => expires: -1 [8] => X-Clockwork-Id: 1464578381.6611.1459882227 [9] => X-Clockwork-Version: 1.11.2 [10] => X-Clockwork-Path: /learninglocker/public/__clockwork/ [11] => Set-Cookie: laravel_session=eyJpdiI6IlFmQUVWaGRZUHZmXC9ibUF2VDRKOUZPVGxBR2tFNXgzWFJtRGdWaFRWcUJ3PSIsInZhbHVlIjoibzh2MWdSTXYrMFkzY1dTRjVXYkZcLzJsd2lnMXVVWXpacVwvYlJcL1wvXC9IamJ5MjR3WjZWSnNnVmh3U0RBUzhGdG9rWDRPaG1SeGp2Rm5IUHZDcW1vVjYzQT09IiwibWFjIjoiMWUxNmUzMzYzZjczNDEwZGY4ZTc0OTNkMDI4MWUyM2ExN2FkMzcwNTc5NzNiYzE2Mjg4ODU2MzI0NjQ2ZmZiMiJ9; expires=Mon, 30-May-2016 05:19:41 GMT; Max-Age=7200; path=/; httponly [12] => Content-Length: 4756 [13] => Connection: close [14] => Content-Type: application/json ) [wrapper_type] => http [stream_type] => tcp_socket/ssl [mode] => rb [unread_bytes] => 0 [seekable] => [uri] => http://localhost:8000/learninglocker/public/data/xAPI/statements?limit=2 ) ) )

**Comment by FrankTrog** [comment]
I made a video going over my setup, what pages I am using to test and other things. 
https://youtu.be/RsjBSskhnSs

**Comment by FrankTrog** [comment]
I did a fresh install from start to finish on a virtual machine on a second computer and it works over there. I must have done something funky on the laptop to get this error. Will try starting over and going through step by step to see if I can get a different result.

**Comment by ryansmith94** [comment]
Hi @FrankTrog, thanks for reporting the issue and using our template, we also really appreciate the video, however, we can't reproduce this issue, we think you may have accidentally modified users via the database.

If you run `db.users.find({})` in Mongo and post that here, we might be able to help you fix any accidental modifications.

**Comment by ryansmith94** [comment]
Closing due to inactivity.

**Comment by manjunath-compassites** [comment]
hi @ryansmith94, i am facing same problem(for API's only), initially it was working but i don't know what happened, now its not working , if i reinstall the project, it will work correctly.

I have attached the screenshot, if its helpful..
any help would be great full.... 

Error message returned :
{"error":true,"success":false,"message":"Argument 1 passed to Illuminate\\Auth\\Guard::setUser() must implement interface Illuminate\\Auth\\UserInterface, null given, called in \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php on line 482 and defined","code":500,"trace":"#0 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php(682): Illuminate\\Exception\\Handler->handleError(4096, 'Argument 1 pass...', '\/home\/vagrant\/C...', 682, Array)\n#1 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Auth\/Guard.php(482): Illuminate\\Auth\\Guard->setUser(NULL)\n#2 [internal function]: Illuminate\\Auth\\Guard->onceUsingId(Object(MongoId))\n#3 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Manager.php(138): call_user_func_array(Array, Array)\n#4 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php(208): Illuminate\\Support\\Manager->__call('onceUsingId', Array)\n#5 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php(208): Illuminate\\Auth\\AuthManager->onceUsingId(Object(MongoId))\n#6 \/home\/vagrant\/Code\/learning\/app\/filters.php(72): Illuminate\\Support\\Facades\\Facade::__callStatic('onceUsingId', Array)\n#7 \/home\/vagrant\/Code\/learning\/app\/filters.php(72): Illuminate\\Support\\Facades\\Auth::onceUsingId(Object(MongoId))\n#8 [internal function]: {closure}(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#9 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Events\/Dispatcher.php(199): call_user_func_array(Object(Closure), Array)\n#10 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Events\/Dispatcher.php(154): Illuminate\\Events\\Dispatcher->fire('router.filter: ...', Array, true)\n#11 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1473): Illuminate\\Events\\Dispatcher->until('router.filter: ...', Array)\n#12 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1435): Illuminate\\Routing\\Router->callRouteFilter('auth.statement', Array, Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#13 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1322): Illuminate\\Routing\\Router->callAttachedBefores(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#14 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1029): Illuminate\\Routing\\Router->callRouteBefore(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#15 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#16 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(775): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#17 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#18 \/home\/vagrant\/Code\/learning\/vendor\/itsgoingd\/clockwork\/Clockwork\/Support\/Laravel\/ClockworkLegacyMiddleware.php(20): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#19 \/home\/vagrant\/Code\/learning\/vendor\/asm89\/stack-cors\/src\/Asm89\/Stack\/Cors.php(51): Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#20 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Asm89\\Stack\\Cors->handle(Object(Illuminate\\Http\\Request), 1, true)\n#21 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#22 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#23 \/home\/vagrant\/Code\/learning\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#24 \/home\/vagrant\/Code\/learning\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#25 \/home\/vagrant\/Code\/learning\/public\/index.php(49): Illuminate\\Foundation\\Application->run()\n#26 {main}"}

and db.users.find({}) :
{
 "_id" : ObjectId("5773ad66bffebc83088b4569"),
"name" : "admin",
"email" : "xyz@gmail.com",
"verified" : "yes", 
"role" : "super", 
"password" : "$2y$10$BCbC3HXqc/Ft3xA1tV7CE.KCVpyYc3hAllO.UHY6JY4pBEHd6z8ha", "updated_at" : ISODate("2016-06-29T11:14:11.553Z"), 
"created_at" : ISODate("2016-06-29T11:13:42.051Z")
}
![body](https://cloud.githubusercontent.com/assets/20183416/16451876/2e7a2f0c-3e23-11e6-8656-b352509f2cfc.png)
![header](https://cloud.githubusercontent.com/assets/20183416/16451875/2e787ce8-3e23-11e6-9908-46e787f999cc.png)

**Comment by manjunath-compassites** [comment]
Hi @ryansmith94,
I have observed one thing, if i deploy the project with out "php artisan migrate" command, the API works fine (POST /data/xAPI/statements). but the admin panel "statements link (menu on the left)" will not work(after statement insertion).

And if i run "php artisan migrate" command then admin panel "statements link (menu on the left)" will work (after statement insertion) but now API won't work  (POST /data/xAPI/statements).

**Learning Locker Version 1.13.1**

![statement menu](https://cloud.githubusercontent.com/assets/20183416/16453030/fb032dda-3e28-11e6-8c8e-21c3b7c4d58c.png)

**Comment by ht2** [comment]
@manjunath-compassites; you will receive this "bad hint" error if you have not run all the migrations as the required indexes have not been created for the hint to work.

The screenshot you have posted; is that for the Statements link failure?

**Comment by manjunath-compassites** [comment]
Hi @ht2, Thanks for replying back.

sorry, i didn't get what do you mean by "Statements link failure"(is it for API or Admin Panel). Last screenshot was for Admin Dashboard's Statement view (http://learninglocker.app/lrs/5773c76abffebc48088b456d/statements).

different user?
i followed the below steps.
-> db.dropDatabase()
->open Admin Dashboard, create new user.
->create new LRS.
->and now if i insert new statement using API(http://tincanapi.com/statement-generator/#tab-smar-sending). it's successful.
->but now Admin Dashboard's Statement view fails.
->by run all the migrations, Admin Dashboard's Statement view shows all the statements.But Api Fails,from here on wards.  

since i drop the data base, i don't get how  `owner_id` on the `$lrs` is a different user....

**Comment by manjunath-compassites** [comment]
and i did check out "owner_id on the $lrs is a different user" the owner_id in LRS collection before migration is
`"owner_id" : ObjectId("5773c750bffebcd2088b4568")`
after the migration is
 `"owner_id" : ObjectId("5774a6ebbffebca9088b4570")`

so i drop the database and rerun the migration file with the below fix. For now its working 

comment this line before migration.

`//$lrs->owner_id = $convertToMongoId($lrs->owner['_id']);`

https://github.com/LearningLocker/learninglocker/blob/develop/app/database/migrations/2015_08_12_150203_ConsistentForeignKeyNames.php#L19

@ht2 Can you please verify the fix, will it cause any issue in long run.

**Comment by ryansmith94** [comment]
I just hit this issue as well and I think it was because I migrated after registering my first user. I think this because afterwards I dropped my database in Mongo, then ran `php artisan migrate`, then registered my user and now everything works fine.

**Comment by ryansmith94** [comment]
Ok so I've looked into this some more and running the migrations after creating your first LRS will cause this issue. The reason is that in new versions of LL, `$lrs->owner['_id']` in the migration linked to by @manjunath-compassites no longer exists, hence `$convertToMongoId($lrs->owner['_id'])` is evaluated to `$convertToMongoId(null)`, which then generates a brand new MongoId that is obviously not an existing user ID, hence the error.

**Comment by ryansmith94** [comment]
@manjunath-compassites commenting out that line should resolve your issue.

**Comment by ryansmith94** [comment]
@ht2 going to add an `isset` check in there to avoid this issue in the future.

**Comment by ryansmith94** [comment]
Hi @manjunath-compassites, this has now been fixed and the fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be available in the next release.

**Comment by manjunath-compassites** [comment]
Thanks a lot @ht2 and @ryansmith94 :+1:
