### ISSUE TITLE
Not able to store Statement

### ISSUE THREAD

**Issue by manjunath-muniraju-4444** [LearningLocker/learninglocker#846]
**v1.13.3**

**Steps to reproduce the bug**
1. git clone -b master git@github.com:LearningLocker/learninglocker.git learning
2. composer install
3. php migrate
4. create user in learnerlocker app(for first time)
5. go to user and check Status to verify
6. create LRS.
7. use API point, username and password from given Manage Clients tab.
8.use PostMan to create statement.
Heading
```
Authorization:Basic ZTNiOTYzZWYwMzM1ZjhkNmRhN2NiY2IzZTZmZTA4Zjg4ZGJmNzE1ODplMmRmZDQxMTMwMWYyZDFmMDMxMzIzYzg3ZmViYmZjZGNkYjc4YWVj
X-Experience-API-Version:1.0.1
Content-Type:application/json
```
Body

  ```
{
  "actor": {
    "name": "Sally Glider",
    "mbox": "mailto:sally@example.com"
  },
  "verb": {
    "id": "http://adlnet.gov/expapi/verbs/experienced",
    "display": { "en-US": "experienced" }
  },
  "object": {
    "id": "http://example.com/activities/solo-hang-gliding",
    "definition": {
      "name": { "en-US": "Solo Hang Gliding" }
    }
  }
}
```

**Expected behaviour**
Should return ID.

**Actual behaviour**
Getting Error:
```
{
  "error": true,
  "success": false,
  "message": "",
  "code": 404,
  "trace": "#0 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\\Routing\\RouteCollection->match(Object(Illuminate\\Http\\Request))\n#1 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\\Routing\\Router->findRoute(Object(Illuminate\\Http\\Request))\n#2 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#3 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#4 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#5 /home/vagrant/Code/test/learning/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkLegacyMiddleware.php(20): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#6 /home/vagrant/Code/test/learning/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(51): Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#7 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Asm89\\Stack\\Cors->handle(Object(Illuminate\\Http\\Request), 1, true)\n#8 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#9 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#10 /home/vagrant/Code/test/learning/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#11 /home/vagrant/Code/test/learning/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#12 /home/vagrant/Code/test/learning/public/index.php(49): Illuminate\\Foundation\\Application->run()\n#13 {main}"
}
```

**Additional information**
OS: Ubuntu 14.04

**Comment by ryansmith94** [comment]
Hi @manjunath-muniraju-4444, thanks for reporting this bug and using our [template](/contributing.md#issue-templates). Can you please tell me what the API endpoint is that you're using?

**Comment by manjunath-muniraju-4444** [comment]
API End Point : `http://learninglocker.app/data/xAPI/`

**Comment by ryansmith94** [comment]
Have you tried `http://learninglocker.app/data/xAPI/statements`?

**Comment by manjunath-muniraju-4444** [comment]
Yes i tried. :-( . Will get different error.....

**Comment by ryansmith94** [comment]
What error is that?

**Comment by manjunath-muniraju-4444** [comment]
Sorry
Its my bad...
`http://learninglocker.app/data/xAPI/statements` **works**

:-)
