### ISSUE TITLE
Error: key https://moodle.org/ must not contain '.' (xapi/node_modules/bson/lib/bson/parser/serializer.js)

### ISSUE THREAD

**Issue by nadavkav** [LearningLocker/learninglocker#966]
2017-09-29 08:36:35:511 - ESC[31merrorESC[39m: a1ad7db0-29cf-4155-8140-76c39e27eeb3 Error: key https://moodle.org/ must not contain '.'
    at Error (native)
    at serializeInto (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:753:19)
    at serializeObject (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at serializeObject (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at serializeObject (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at serializeObject (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at serializeObject (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:618:17)
    at serializeObject (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at BSON.serialize (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/bson/lib/bson/bson.js:58:27)
    at Query.toBin (/usr/local/learninglocker/releases/ll-20170929-fff2f83b60ec5ada8d0e6ac029cb0adb5cde4a57/xapi/node_modules/mongodb-core/lib/connection/commands.js:140:25)

**Version**
{{branch}} at {{commit}} on 2.0.1
(Installed on a vanilla Debian 9, using the following instructions: http://docs.learninglocker.net/guides-installing/ with out any errors during install)

**Steps to reproduce the bug**
1. Create a new xAPI client for a Moodle system
2. Install Moodle 3rd party xapi_logstore plugin, and configure it to send xapi statements to LLv2

**Expected behaviour**
See Moodle xapi statements in LLv2

**Actual behaviour**
Nothing seen on the LLv2 Dashboard.
(Also, not sure how to monitor it, and see raw statements)

**Additional information**
OS: Debian 9
Browser: Version 57.0.2987.133 (64-bit)

**Comment by ryansmith94** [comment]
Hey @nadavkav, thanks for reporting this issue. I'm just going to have a look at the Moodle plugin to try and understand where that is coming from. I'll get back to you.

**Comment by ryansmith94** [comment]
Hey @nadavkav, looking through the Moodle Plugin I can see the [following code in one of the examples](https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/lib/emitter/docs/examples/assignment_graded.json#L18).

```json
    "context": {
        "platform": "Moodle",
        "language": "en",
        "extensions": {
            "http:\/\/www.example.com\/context_ext_key": {
                "test_context_ext_key": "test_context_ext_value"
            },
            "http:\/\/lrs.learninglocker.net\/define\/extensions\/info": {
                "https:\/\/moodle.org\/": "1.0.0"
            }
        }
    }
```

Whilst we replace the dots in the extension keys (e.g. `http:\/\/lrs.learninglocker.net\/define\/extensions\/info`) we haven't replaced the dots inside those individual extensions.

To resolve this, we'll need to make some changes to the [replaceDotsInStatement util](https://github.com/LearningLocker/xapi-statements/blob/97ece1c073cf2d24b40966e29d7d75d509383632/src/mongoModelsRepo/utils/replaceDotsInStatement.ts). I'll try to get that fixed and tested now. I'll report back here.

**Comment by ryansmith94** [comment]
@nadavkav LearningLocker/xapi-statements#46 contains a fix for your issue. It's currently awaiting a review from @ht2. I'll let you know when you can upgrade your Learning Locker to get the fix 👍

**Comment by ryansmith94** [comment]
Hi @nadavkav, you should be able to run the [installation command again](http://docs.learninglocker.net/guides-installing/) to upgrade.

**Comment by ryansmith94** [comment]
For the record this was fixed in [xapi-service@1.0.3](https://github.com/LearningLocker/xapi-service/releases/tag/v1.0.3)

**Comment by nadavkav** [comment]
Thank you @ryanrolds for your quick reply and fix! I updated and everything works just fine :-)

**Comment by ryansmith94** [comment]
You're welcome! That's great @nadavkav, thanks for letting us know 👍
